maintainer			"Kyle Bader"
maintainer_email	"kyle.bader@dreamhost.com"
license				"Apache 2.0"
description			"Installs/Configures the Ceph distributed filesystem"
version				"1.0.2"
depends				"apache2"
depends				"apt"
depends				"btrfs"
depends				"parted"
depends				"xfs"
depends				"logrotate"
